<?php

/**
 * BaseTotalUsage
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $count
 * @property integer $input_bits
 * @property integer $output_bits
 * 
 * @method integer    getCount()       Returns the current record's "count" value
 * @method integer    getInputBits()   Returns the current record's "input_bits" value
 * @method integer    getOutputBits()  Returns the current record's "output_bits" value
 * @method TotalUsage setCount()       Sets the current record's "count" value
 * @method TotalUsage setInputBits()   Sets the current record's "input_bits" value
 * @method TotalUsage setOutputBits()  Sets the current record's "output_bits" value
 * 
 * @package    pppoe
 * @subpackage model
 * @author     Ariunbayar
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTotalUsage extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('total_usage');
        $this->hasColumn('count', 'integer', null, array(
             'type' => 'integer',
             'default' => 0,
             ));
        $this->hasColumn('input_bits', 'integer', null, array(
             'type' => 'integer',
             'default' => 0,
             ));
        $this->hasColumn('output_bits', 'integer', null, array(
             'type' => 'integer',
             'default' => 0,
             ));

        $this->option('type', 'MYISAM');
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable(array(
             'updated' => 
             array(
              'disabled' => true,
             ),
             ));
        $this->actAs($timestampable0);
    }
}