<?php

/**
 * BaseDistrict
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property Doctrine_Collection $Customers
 * @property Doctrine_Collection $ChangeLogs
 * 
 * @method string              getName()       Returns the current record's "name" value
 * @method Doctrine_Collection getCustomers()  Returns the current record's "Customers" collection
 * @method Doctrine_Collection getChangeLogs() Returns the current record's "ChangeLogs" collection
 * @method District            setName()       Sets the current record's "name" value
 * @method District            setCustomers()  Sets the current record's "Customers" collection
 * @method District            setChangeLogs() Sets the current record's "ChangeLogs" collection
 * 
 * @package    pppoe
 * @subpackage model
 * @author     Ariunbayar
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseDistrict extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('district');
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));

        $this->option('type', 'MYISAM');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Customer as Customers', array(
             'local' => 'id',
             'foreign' => 'district_id'));

        $this->hasMany('ChangeLog as ChangeLogs', array(
             'local' => 'id',
             'foreign' => 'object_id'));
    }
}