<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Radpostauth', 'doctrine');

/**
 * BaseRadpostauth
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $username
 * @property string $pass
 * @property string $reply
 * @property timestamp $authdate
 * 
 * @method integer     getId()       Returns the current record's "id" value
 * @method string      getUsername() Returns the current record's "username" value
 * @method string      getPass()     Returns the current record's "pass" value
 * @method string      getReply()    Returns the current record's "reply" value
 * @method timestamp   getAuthdate() Returns the current record's "authdate" value
 * @method Radpostauth setId()       Sets the current record's "id" value
 * @method Radpostauth setUsername() Sets the current record's "username" value
 * @method Radpostauth setPass()     Sets the current record's "pass" value
 * @method Radpostauth setReply()    Sets the current record's "reply" value
 * @method Radpostauth setAuthdate() Sets the current record's "authdate" value
 * 
 * @package    pppoe
 * @subpackage model
 * @author     Ariunbayar
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseRadpostauth extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('radpostauth');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('username', 'string', 64, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 64,
             ));
        $this->hasColumn('pass', 'string', 64, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 64,
             ));
        $this->hasColumn('reply', 'string', 32, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 32,
             ));
        $this->hasColumn('authdate', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}