<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2011/01/28 00:06:04
sfConfig::add(array(
  'app_client_ip' => '127.0.0.1',
  'app_client_username' => 'incris',
  'app_client_password' => 'incris153',
  'app_client_token' => 'L7EbhniYjNeph0viU56Y',
  'app_max_customers' => 20,
  'app_max_changelogs' => 20,
  'app_roles' => array (
  'users' => 'Админууд',
  'user_new_edit' => 'Админийг нэмэх, засах',
  'user_delete' => 'Админийг устгах',
  'customers' => 'Хэрэглэгчид',
  'customer_new_edit' => 'Хэрэглэгч нэмэх, засах',
  'customer_delete' => 'Хэрэглэгч устгах',
  'district_new_edit' => 'Хорооллууд нэмэх, засах',
  'district_delete' => 'Хорооллууд устгах',
  'changelog' => 'Түүх',
  'management' => 'Maintenance',
  'total_usage' => 'Хэрэглээ',
  'ipsetting' => 'Тохиргоо',
),
));
