<?php
// auto-generated by sfSecurityConfigHandler
// date: 2011/01/28 00:06:04
$this->security = array (
  'all' => 
  array (
    'is_secure' => true,
    'credentials' => 
    array (
      0 => 
      array (
        0 => 'ipsetting',
      ),
    ),
  ),
);
