<?php

/**
 * ConfigTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ConfigTable extends Doctrine_Table
{
  /**
   * Returns an instance of this class.
   *
   * @return object ConfigTable
   */
  public static function getInstance()
  {
    return Doctrine_Core::getTable('Config');
  }

  public static function getConfig($name)
  {
    $config = self::getInstance()->findOneByName($name);
    if ($config) return $config->getValue();
    return null;
  }

  public static function setConfig($name, $value)
  {
    $config = self::getInstance()->findOneByName($name);
    if (!$config) {
      $config = new Config();
      $config->setName($name);
    }
    $config->setValue($value);
    $config->save();
  }
}