<?php

/**
 * NextActionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class NextActionTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object NextActionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('NextAction');
    }
}