<?php

/**
 * Radacct
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    pppoe
 * @subpackage model
 * @author     Ariunbayar
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Radacct extends BaseRadacct
{
  /**
   * @return Customer
   */
  public function getCustomer()
  {
    $customer = Doctrine_Core::getTable('Customer')->findOneByUsername($this->getUsername());
    return $customer;
  }
}
