<?php

/**
 * RadcheckTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class RadcheckTable extends Doctrine_Table
{
  /**
   * Returns an instance of this class.
   *
   * @return object RadcheckTable
   */
  public static function getInstance()
  {
      return Doctrine_Core::getTable('Radcheck');
  }

  public static function userExists($username)
  {
    return Doctrine_Core::getTable('Radcheck')->createQuery('rc')
            ->where('rc.username LIKE ?', $username)
            ->count();
  }

  public static function updateUsername($old, $new)
  {
    Doctrine_Core::getTable('Radcheck')->createQuery('rc')
            ->update()
            ->set('rc.username', '?', $new)
            ->where('rc.username LIKE ?', $old)
            ->execute();
  }
}