<?php

/**
 * RadpostauthTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class RadpostauthTable extends Doctrine_Table
{
  /**
   * Returns an instance of this class.
   *
   * @return object RadpostauthTable
   */
  public static function getInstance()
  {
      return Doctrine_Core::getTable('Radpostauth');
  }

  public static function userExists($username)
  {
    return Doctrine_Core::getTable('Radpostauth')->createQuery('rp')
            ->where('rp.username LIKE ?', $username)
            ->andWhere('rp.reply LIKE ?', 'Access-Accept')
            ->count();
  }

  public static function updateUsername($old, $new)
  {
    Doctrine_Core::getTable('Radpostauth')->createQuery('rp')
            ->update()
            ->set('rp.username', '?', $new)
            ->where('rp.username LIKE ?', $old)
            ->andWhere('rp.reply LIKE ?', 'Access-Accept')
            ->execute();
  }
}