<?php

/**
 * RadusergroupTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class RadusergroupTable extends Doctrine_Table
{
  /**
   * Returns an instance of this class.
   *
   * @return object RadusergroupTable
   */
  public static function getInstance()
  {
      return Doctrine_Core::getTable('Radusergroup');
  }

  public static function userExists($username)
  {
    return Doctrine_Core::getTable('Radusergroup')->createQuery('ru')
            ->where('ru.username LIKE ?', $username)
            ->count();
  }

  public static function updateUsername($old, $new)
  {
    Doctrine_Core::getTable('Radusergroup')->createQuery('ru')
            ->update()
            ->set('ru.username', '?', $new)
            ->where('ru.username LIKE ?', $old)
            ->execute();
  }
}