<?php

/**
 * ChangeLogTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ChangeLogTable extends Doctrine_Table
{
  /**
   * Returns an instance of this class.
   *
   * @return object ChangeLogTable
   */
  public static function getInstance()
  {
      return Doctrine_Core::getTable('ChangeLog');
  }

  public static function saveNew($obj_id, $obj, $msg, $editor_id)
  {
    $changelog = new ChangeLog();
    $changelog->setObjectId($obj_id);
    $changelog->setObject($obj);
    $changelog->setDescription($msg);
    $changelog->setEditorId($editor_id);
    $changelog->save();
  }
}