<?php

/**
 * DistrictTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DistrictTable extends Doctrine_Table
{
  /**
   * Returns an instance of this class.
   *
   * @return object DistrictTable
   */
  public static function getInstance()
  {
    return Doctrine_Core::getTable('District');
  }

  public static function getAssoc()
  {
    $dql = self::getInstance()->createQuery('a')->orderBy('a.name');
    $districts = $dql->execute();
    $arr = array();
    foreach ($districts as $district) {
      $arr[$district->getId()] = $district->getName();
    }

    return $arr;
  }
}