<?php

/**
 * NasTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class NasTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object NasTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Nas');
    }
}