<?php

/**
 * PhoneTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PhoneTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PhoneTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Phone');
    }
}