<?php

/**
 * RadacctTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class RadacctTable extends Doctrine_Table
{
  /**
   * Returns an instance of this class.
   *
   * @return object RadacctTable
   */
  public static function getInstance()
  {
      return Doctrine_Core::getTable('Radacct');
  }

  public static function userExists($username)
  {
    return Doctrine_Core::getTable('Radacct')->createQuery('ra')
            ->where('ra.username LIKE ?', $username)
            ->count();
  }

  public static function updateUsername($old, $new)
  {
    Doctrine_Core::getTable('Radacct')->createQuery('ra')
            ->update()
            ->set('ra.username', '?', $new)
            ->where('ra.username LIKE ?', $old)
            ->execute();
  }
}