<?php

/**
 * RadippoolTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class RadippoolTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object RadippoolTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Radippool');
    }
}