<?php

/**
 * TotalUsageTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TotalUsageTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TotalUsageTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TotalUsage');
    }
}