<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2011/01/28 16:12:10

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=ispadmin_pppoe',
  'username' => 'root',
  'password' => 'incris^671',
  'name' => 'doctrine',
)),);
