<?php
// auto-generated by sfSecurityConfigHandler
// date: 2011/01/28 16:12:10
$this->security = array (
  'index' => 
  array (
    'credentials' => 
    array (
      0 => 
      array (
        0 => 'customers',
      ),
    ),
  ),
  'new' => 
  array (
    'credentials' => 
    array (
      0 => 
      array (
        0 => 'customer_new_edit',
      ),
    ),
  ),
  'create' => 
  array (
    'credentials' => 
    array (
      0 => 
      array (
        0 => 'customer_new_edit',
      ),
    ),
  ),
  'edit' => 
  array (
    'credentials' => 
    array (
      0 => 
      array (
        0 => 'customer_new_edit',
      ),
    ),
  ),
  'update' => 
  array (
    'credentials' => 
    array (
      0 => 
      array (
        0 => 'customer_new_edit',
      ),
    ),
  ),
  'delete' => 
  array (
    'credentials' => 
    array (
      0 => 
      array (
        0 => 'customer_delete',
      ),
    ),
  ),
  'all' => 
  array (
    'is_secure' => true,
  ),
);
