<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Radippool', 'doctrine');

/**
 * BaseRadippool
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $pool_name
 * @property string $framedipaddress
 * @property string $nasipaddress
 * @property string $calledstationid
 * @property string $callingstationid
 * @property timestamp $expiry_time
 * @property string $username
 * @property string $pool_key
 * 
 * @method integer   getId()               Returns the current record's "id" value
 * @method string    getPoolName()         Returns the current record's "pool_name" value
 * @method string    getFramedipaddress()  Returns the current record's "framedipaddress" value
 * @method string    getNasipaddress()     Returns the current record's "nasipaddress" value
 * @method string    getCalledstationid()  Returns the current record's "calledstationid" value
 * @method string    getCallingstationid() Returns the current record's "callingstationid" value
 * @method timestamp getExpiryTime()       Returns the current record's "expiry_time" value
 * @method string    getUsername()         Returns the current record's "username" value
 * @method string    getPoolKey()          Returns the current record's "pool_key" value
 * @method Radippool setId()               Sets the current record's "id" value
 * @method Radippool setPoolName()         Sets the current record's "pool_name" value
 * @method Radippool setFramedipaddress()  Sets the current record's "framedipaddress" value
 * @method Radippool setNasipaddress()     Sets the current record's "nasipaddress" value
 * @method Radippool setCalledstationid()  Sets the current record's "calledstationid" value
 * @method Radippool setCallingstationid() Sets the current record's "callingstationid" value
 * @method Radippool setExpiryTime()       Sets the current record's "expiry_time" value
 * @method Radippool setUsername()         Sets the current record's "username" value
 * @method Radippool setPoolKey()          Sets the current record's "pool_key" value
 * 
 * @package    pppoe
 * @subpackage model
 * @author     Ariunbayar
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseRadippool extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('radippool');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('pool_name', 'string', 30, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 30,
             ));
        $this->hasColumn('framedipaddress', 'string', 15, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 15,
             ));
        $this->hasColumn('nasipaddress', 'string', 15, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 15,
             ));
        $this->hasColumn('calledstationid', 'string', 30, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 30,
             ));
        $this->hasColumn('callingstationid', 'string', 30, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 30,
             ));
        $this->hasColumn('expiry_time', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0000-00-00 00:00:00',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('username', 'string', 64, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 64,
             ));
        $this->hasColumn('pool_key', 'string', 30, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 30,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}