<?php

/**
 * BaseNextAction
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $customer_id
 * @property string $action
 * @property datetime $date
 * @property Customer $Customer
 * 
 * @method integer    getCustomerId()  Returns the current record's "customer_id" value
 * @method string     getAction()      Returns the current record's "action" value
 * @method datetime   getDate()        Returns the current record's "date" value
 * @method Customer   getCustomer()    Returns the current record's "Customer" value
 * @method NextAction setCustomerId()  Sets the current record's "customer_id" value
 * @method NextAction setAction()      Sets the current record's "action" value
 * @method NextAction setDate()        Sets the current record's "date" value
 * @method NextAction setCustomer()    Sets the current record's "Customer" value
 * 
 * @package    pppoe
 * @subpackage model
 * @author     Ariunbayar
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseNextAction extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('next_action');
        $this->hasColumn('customer_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('action', 'string', 50, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 50,
             ));
        $this->hasColumn('date', 'datetime', null, array(
             'type' => 'datetime',
             'notnull' => true,
             ));

        $this->option('type', 'MYISAM');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Customer', array(
             'local' => 'customer_id',
             'foreign' => 'id'));
    }
}