<?php

/**
 * BasePhone
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $customer_id
 * @property string $description
 * @property Customer $Customer
 * 
 * @method integer  getCustomerId()  Returns the current record's "customer_id" value
 * @method string   getDescription() Returns the current record's "description" value
 * @method Customer getCustomer()    Returns the current record's "Customer" value
 * @method Phone    setCustomerId()  Sets the current record's "customer_id" value
 * @method Phone    setDescription() Sets the current record's "description" value
 * @method Phone    setCustomer()    Sets the current record's "Customer" value
 * 
 * @package    pppoe
 * @subpackage model
 * @author     Ariunbayar
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePhone extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('phone');
        $this->hasColumn('customer_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('description', 'string', 50, array(
             'type' => 'string',
             'length' => 50,
             ));

        $this->option('type', 'MYISAM');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Customer', array(
             'local' => 'customer_id',
             'foreign' => 'id'));
    }
}