<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Radcheck', 'doctrine');

/**
 * BaseRadcheck
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $username
 * @property string $attr
 * @property string $op
 * @property string $value
 * 
 * @method integer  getId()       Returns the current record's "id" value
 * @method string   getUsername() Returns the current record's "username" value
 * @method string   getAttr()     Returns the current record's "attr" value
 * @method string   getOp()       Returns the current record's "op" value
 * @method string   getValue()    Returns the current record's "value" value
 * @method Radcheck setId()       Sets the current record's "id" value
 * @method Radcheck setUsername() Sets the current record's "username" value
 * @method Radcheck setAttr()     Sets the current record's "attr" value
 * @method Radcheck setOp()       Sets the current record's "op" value
 * @method Radcheck setValue()    Sets the current record's "value" value
 * 
 * @package    pppoe
 * @subpackage model
 * @author     Ariunbayar
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseRadcheck extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('radcheck');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('username', 'string', 64, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 64,
             ));
        $this->hasColumn('attr', 'string', 32, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 32,
             ));
        $this->hasColumn('op', 'string', 2, array(
             'type' => 'string',
             'fixed' => 1,
             'unsigned' => false,
             'primary' => false,
             'default' => '==',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 2,
             ));
        $this->hasColumn('value', 'string', 253, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 253,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}